name: Generate Library CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 0 * * 0

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  generate-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
      - id: install
        name: Install dependencies
        run: dart pub get
        working-directory: scripts
      - name: Generate library
        run: dart scripts/bin/generate_library.dart
